function renderAlertsList() { const ur = document.getElementById("alerts-unresolved"), re = document.getElementById("alerts-resolved"); if (!ur || !re) return; const un = alerts.filter(a => !a.resolved), rs = alerts.filter(a => a.resolved); ur.innerHTML = un.length ? "" : '<div class="empty-state"><div class="icon">✅</div><p>All clear</p></div>'; un.forEach(a => { ur.innerHTML += `<div class="alert-item"><div class="alert-icon ${a.type === "collected" ? "collected-icon" : "warning"}">${a.type === "collected" ? "📦" : "⚠️"}</div><div style="flex:1"><div class="alert-text"><strong>${a.type === "collected" ? "Collected (" + a.studentId + ")" : "Unattended"}</strong> at <strong>${a.table_id}</strong></div><div class="alert-time">${a.timestamp}</div><button class="btn btn-green btn-sm" style="margin-top:6px" onclick="alerts.find(x=>x.id===${a.id}).resolved=true;renderTab();">Resolve</button></div></div>`; }); re.innerHTML = rs.length ? "" : '<div class="empty-state"><div class="icon">📭</div><p>None yet</p></div>'; rs.forEach(a => { re.innerHTML += `<div class="alert-item"><div class="alert-icon resolved">✅</div><div style="flex:1"><div class="alert-text"><strong>Resolved</strong> — ${a.table_id}</div><div class="alert-time">${a.timestamp}</div></div></div>`; }); }

function renderIssuesList() { const open = document.getElementById("issues-open-count"); if (open) open.textContent = `${issues.filter(i => i.status === "Open").length} open`; const p = document.getElementById("issues-list"); if (!p) return; if (!issues.length) { p.innerHTML = '<div class="empty-state"><div class="icon">🔧</div><p>No issues reported</p></div>'; return; } p.innerHTML = ""; issues.forEach(i => { p.innerHTML += `<div class="issue-item"><div class="issue-info"><h4>${i.component}</h4><p>${i.description}</p><div class="issue-date">${i.date} · Priority: ${i.priority}</div></div><div><span class="badge ${i.status === "Open" ? "open-b" : "resolved-b"}">${i.status}</span>${i.status === "Open" ? ` <button class="btn btn-green btn-sm" style="margin-left:6px" onclick="issues.find(x=>x.id===${i.id}).status='Resolved';renderTab();">Resolve</button>` : ""}</div></div>`; }); }
function openReportIssue() { openModal("Report Issue", `
  <div class="form-group"><label>Component</label><select id="ri-comp"><option>RFID Reader</option><option>Barcode Scanner</option><option>Camera Module</option>${seats.map(s => `<option>FSR Sensor - ${s.id}</option>`).join("")}<option>Raspberry Pi</option><option>Network</option><option>Other</option></select></div>
  <div class="form-group"><label>Description</label><textarea id="ri-desc" placeholder="Describe the issue..."></textarea></div>
  <div class="form-group"><label>Priority</label><select id="ri-pri"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div>`,
  `<button class="btn btn-ghost" onclick="closeModal()">Cancel</button><button class="btn btn-amber" onclick="submitIssue()">Submit</button>`); }
function submitIssue() { const c = document.getElementById("ri-comp").value, d = document.getElementById("ri-desc").value.trim(), p = document.getElementById("ri-pri").value; if (!d) return showToast("Add description", "danger"); issues.push({ id: issues.length + 1, component: c, description: d, priority: p, status: "Open", date: new Date().toLocaleString() }); closeModal(); showToast("Issue reported", "success"); renderTab(); }
